### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by todoubled** [hellodigit/node-intuit#2]
- [x] code example in readme (https://github.com/hellodigit/node-intuit/pull/6)
- [x] swap XML parsing for actual JSON responses (https://github.com/hellodigit/node-intuit/pull/7)
- [x] tests for each `GET`/`DELETE` method with fixtures from real API calls (https://github.com/hellodigit/node-intuit/pull/7)
- [x] tests for each `POST`/`PUT` method with fixtures from real API calls (https://github.com/hellodigit/node-intuit/pull/7)
- [x] handle error status codes (https://developer.intuit.com/docs/0020_customeraccountdata/customer_account_data_api/0700_error_codes)
- [ ] handle OAuth token expiration (https://github.com/hellodigit/node-intuit/issues/8)
